Numpy --> Numerical Python

Why use Numpy?

1. Really helpful in doing mathematical operations
2. Time taken is more efficient compared to normal python features

Selengkapnya bisa dicari di Numpy Documentation

In [10]:
import numpy as np

List vs Numpy - Time Taken

In [11]:
from time import process_time

Time taken by a List

In [14]:
python_list = list(range(1000000))

start_time = process_time()

python_list = [x+5 for x in python_list]

end_time = process_time()

print(f"Time taken to double each element in the list: {end_time - start_time} seconds")

Time taken to double each element in the list: 0.078125 seconds


Time taken by Numpy

In [15]:
np_array = np.arange(1000000)

start_time = process_time()

np_array += 5

end_time = process_time()

print(f"Time taken to double each element in the NumPy array: {end_time - start_time} seconds")

Time taken to double each element in the NumPy array: 0.0 seconds


Numpy Arrays

In [16]:
#List
list1 = [1, 2, 3, 4, 5]
print("List:", list1)
type(list1)

List: [1, 2, 3, 4, 5]


list

In [17]:
np_array = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", np_array)
type(np_array)

NumPy Array: [1 2 3 4 5]


numpy.ndarray

In [19]:
# Creating a 1 dim array
a = np.array([1, 2, 3, 4, 5])
print(a.shape)

(5,)


In [24]:
#Creating a multi dim array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype='float32')
print(b.shape)

(4, 3)


Initial Placeholders in numpy arrays

In [27]:
# Create a numpy array with zeros
c = np.zeros((3, 4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# Create a numpy array with ones
d = np.ones((3, 4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
# Create array of particular value
e = np.full((3, 4), 7)
e

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [30]:
# Create an identity matrix
f = np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Create an array with random values
g = np.random.random((3, 4)) # The value only between 0 and 1
g

array([[0.2199136 , 0.48701088, 0.36559973, 0.55826918],
       [0.44227586, 0.64403158, 0.81361703, 0.93145837],
       [0.52505768, 0.62920431, 0.66668649, 0.54030607]])

In [36]:
# Random integer values array within a specific range
h = np.random.randint(0, 10, (3, 4)) # The value between 0 and 10
h

array([[8, 4, 5, 2],
       [9, 7, 0, 0],
       [0, 6, 5, 0]])

In [ ]:
# Array of evenly spaced values --> specifying the number of step
i = np.arange(0, 10, 2) # Start, stop (not included), step
print(i)

[0 2 4 6 8]


In [38]:
# Array of evenly spaced values --> specifying the number of elements
j = np.linspace(0, 10, 5) # Start, stop, number of elements
print(j)

[ 0.   2.5  5.   7.5 10. ]


In [41]:
# Convert a list to a numpy array
list2 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

np_array_from_list = np.asarray(list2)
print("NumPy Array from List:", np_array_from_list)
print(type(np_array_from_list))

# Convert a numpy array to a list
np_array_to_list = np_array_from_list.tolist()
print("List from NumPy Array:", np_array_to_list)
print(type(np_array_to_list))

NumPy Array from List: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>
List from NumPy Array: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
<class 'list'>


Analysing Numpy array

In [47]:
k = np.random.randint(0, 90, (5, 5, 5))

In [48]:
print(f"shape: {k.shape}")
print(f"size: {k.size}")
print(f"ndim: {k.ndim}")
print(f"dtype: {k.dtype}")

shape: (5, 5, 5)
size: 125
ndim: 3
dtype: int32


Mathematical Operation on np array

In [49]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

print(list1 + list2)  # Concatenation of lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [52]:
np_array1 = np.array([1, 2, 3, 4, 5])
np_array2 = np.array([6, 7, 8, 9, 10])

print(np_array1 + np_array2)  # Element-wise addition of NumPy arrays
print(np_array1 * np_array2)  # Element-wise multiplication of NumPy arrays
print(np_array1 - np_array2)  # Element-wise subtraction of NumPy arrays
print(np_array1 / np_array2)  # Element-wise division of NumPy arrays
print(np_array1 ** np_array2)  # Element-wise squaring of NumPy array
print(np_array1 @ np_array2)  # Dot product of NumPy arrays

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[-5 -5 -5 -5 -5]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]
130
